name: Node.js CI

on: [push, pull_request]

jobs:
  examine:
    runs-on: ubuntu-latest
    name: Lint and test

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn ci
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn testci
    - name: Upload coverage
      uses: codecov/codecov-action@master
